version: '3'
services:
  nfs:
    image: d0whc3r/nfs-server-alpine:latest
    privileged: true
    volumes:
      - /some/where/fileshare:/nfsshare
    environment: 
      - SHARED_DIRECTORY=/nfsshare
    ports:
      - 2049:2049
